version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:latest
    container_name: "mysql"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      #senha do mysql
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      custom_network:
        ipv4_address: 172.20.0.3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: "phpmyadmin"
    depends_on:
      - db
    ports:
      - 8000:80
    networks: 
      custom_network:
        ipv4_address: 172.20.0.2  
networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24