version: '3.7'
services:
  postgres:
    image: postgres
    env_file: 
      - .env
    volumes:
      - "./postgres/bk:/bk"
      - "./postgres/data:/var/lib/postgresql/data"
      - "./scripts:/scripts"
    network_mode: host
  pgadmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - postgres
    network_mode: host

